### ISSUE TITLE
"npm start" fails with Error: not logged in

### ISSUE THREAD

**Issue by mediadog** [mozilla/hubs#2404]
**Description**
I followed the instructions in the main page to build a local copy of Hubs (which omits listing node.js as a prerequisite btw), but am unable to start the local instance.

**To Reproduce**
As listed in the "Getting Started" section to run the local client:
git clone https://github.com/mozilla/hubs.git
cd hubs
npm ci
npm start

The "npm start" results in:

D:\hubs\hubs> npm start

> hubs@0.0.1 start D:\hubs\hubs
> webpack-dev-server --mode=development --env.loadAppConfig

Error: Not logged in to Hubs Cloud. Run `npm login` first.
    at fetchAppConfigAndEnvironmentVars (D:\hubs\hubs\webpack.config.js:115:11)
    at module.exports (D:\hubs\hubs\webpack.config.js:177:27)
    at handleFunction (D:\hubs\hubs\node_modules\webpack-cli\bin\prepareOptions.js:21:13)
    at prepareOptions (D:\hubs\hubs\node_modules\webpack-cli\bin\prepareOptions.js:9:5)
    at requireConfig (D:\hubs\hubs\node_modules\webpack-cli\bin\convert-argv.js:118:14)
    at D:\hubs\hubs\node_modules\webpack-cli\bin\convert-argv.js:124:17
    at Array.forEach (<anonymous>)
    at module.exports (D:\hubs\hubs\node_modules\webpack-cli\bin\convert-argv.js:122:15)
    at Object.<anonymous> (D:\hubs\hubs\node_modules\webpack-dev-server\bin\webpack-dev-server.js:92:55)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Expected behavior**
I assume I would get some notice that the client had started running.  There us is no mention in the "Getting Started" about having to log into an account anywhere.

**Hardware** 
 - Alienware 13 R3
 - OS: Windows 10 Pro x64
 - Browser N/A, not getting that far

**Additional context**

**Comment by misslivirose** [comment]
There's a PR up to update the readme with information from this change: https://github.com/mozilla/hubs/pull/2340 - this was just updated a couple days ago. @robertlong - should `npm start` work per the old process if you've never run `npm run dev`? 

@mediadog - I think you'll want to run `npm run <server option>` per 2340. If you're working on a client fork against our development infrastructure, that's `npm run dev` instead of `npm start` (at least, this is what I just tested after hitting the issue you saw with `npm start`) 

If you're using a Hubs Cloud server as your backend, the instructions are slightly different but documented in 2340. 

#2403 is the update for the readme/contributing files.

**Comment by mediadog** [comment]
Thanks, `npm run dev` did get things running locally.  Being a newbie, not sure what some of discussed in #2340 is talking about (specifically sounds like the configuration appears to not be modifiable if not a reticulum admin) but will delve in further now that I can run something.  Thanks again!
