### ISSUE TITLE
iframe embedding not working in secure contexts such as incognito mode

### ISSUE THREAD

**Issue by rawnsley** [mozilla/hubs#3911]
In [this simple example](https://alpha.avncloud.com/dev/persistent/hubs-iframe-bug.html) of a Hubs room embedded in an iframe the room loads fine in normal browser mode, but fails to load when viewed in Chrome's Incognito mode. It has also been reported on normal Chrome sessions, possibly where the user has adopted a more restricted default security model.

It appears to be because [access to the `localStorage` API is blocked](https://www.chromium.org/for-testers/bug-reporting-guidelines/uncaught-securityerror-failed-to-read-the-localstorage-property-from-window-access-is-denied-for-this-document) and an exception is thrown in [store.js](https://github.com/mozilla/hubs/blob/master/src/storage/store.js) like this:

```
store.js:215 Uncaught DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document.
    at new C (https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:1082953)
    at new i (https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:1085762)
    at Module.1666 (https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:924116)
    at o (https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:561)
    at n (https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:430)
    at https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:2534
    at https://assets-prod.reticulum.io/hubs/assets/js/hub-596e542bb782311ce205.js:1:2538
```
A causal search has yielded no obvious way around the problem. There is an [experimental option to prompt the user for access](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API/Using), but it would be hard to provide any meaningful context to the question, not to mention the friction it would create.

One solution would be more graceful fallback behaviour when `localStorage` is not available. Perhaps simply storing the data in an in-memory javascript map?

It does not appear to be a problem in Firefox's Private browsing mode.

Test platform: Chrome Version 89.0.4389.47 (Official Build) beta (x86_64) on MacOS

**Comment by robertlong** [comment]
Hey @rawnsley thanks for the PR. Is this something you've been running into in your own work?

We've looked at this code and the localstorage mock is interesting. Perhaps we could polyfill localstorage with that mock instead? I'm not sure. Definitely something I'd like to discuss more and get your take.

**Comment by rawnsley** [comment]
@robertlong I ended up running a modified version [as seen here](https://github.com/LearnHub/hubs/commit/c3342cda0d46c346a1d1df8c266a1f3414288084). As I mentioned in the PR, the npm login task (and probably a few others) depends on store.js so I moved the guts of the change into there. The change is live and is running successfully.

Unfortunately you can't polyfill the `localstorage` parameter directly because the exception is triggered simply by accessing it. For this reason I ended up with the rather ugly pseudo-polyfill parameter `safeLocalStorage`.

Personally I would encapsulate `localstorage` access into the Store class and hide the implementation detail in there. This would also give you more flexibility in future if you wanted to migrate parameter names or perhaps for situations like [this recent issue](https://github.com/mozilla/hubs/issues/3931). I'm an OO guy at heart though and to a man with a hammer everything looks like a nail :-)

**Comment by robertlong** [comment]
> Personally I would encapsulate localstorage access into the Store class and hide the implementation detail in there.

Yes, I think that's the right thing to do. If it's alright I'm going to close the PR you have outstanding and I'll look into adding proper checks to the store class.
