### ISSUE TITLE
`TypeError: Cannot read property 'enableMicrophone' of undefined` error (in `src/components/mute-mic.js`)

### ISSUE THREAD

**Issue by cvan** [mozilla/hubs#394]
```
TypeError: Cannot read property 'enableMicrophone' of undefined
  at enableMicrophone(./src/components/mute-mic.js:52:29)
  at apply(./node_modules/raven-js/src/raven.js:360:0)
  at dispatchEvent(src/core/a-node.js:297:15)
  at emit(./src/components/in-world-hud.js:30:14)
  at apply(./node_modules/raven-js/src/raven.js:360:0)
  at dispatchEvent(./node_modules/super-hands/index.js:492:0)
  at dispatchMouseEvent(./node_modules/super-hands/index.js:186:0)
  at apply(./node_modules/raven-js/src/raven.js:360:0)
  at dispatchEvent(src/core/a-node.js:297:15)
  at emit(./src/components/cursor-controller.js:347:21)
  at apply(./node_modules/raven-js/src/raven.js:360:0)
```

![screenshot](https://user-images.githubusercontent.com/203725/40205070-506b8986-59f0-11e8-9456-83f8ed147723.png)

**Comment by brianpeiris** [comment]
Steps to repro:
1. In Google Chrome, set CPU throttling to "6x slowdown" under the Performance tab settings
2. Load a hub room
3. While the page is loading, click on the background multiple times
4. Note the errors logged in the console
