### ISSUE TITLE
Running mozilla hubs build on AWS Cloud 9

### ISSUE THREAD

**Issue by jeffrobernard** [mozilla/hubs#410]
Hello, 
After doing the install to AWS Cloud 9, the errors below pop up in the console. What might be the solution to these errors? thanks in advance. 
npm ERR! Linux 4.14.33-51.37.amzn1.x86_64
npm ERR! argv "/home/ec2-user/.nvm/versions/node/v6.14.2/bin/node" "/home/ec2-user/.nvm/versions/node/v6.14.2/bin/npm" "run" "start"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! mr-social-client@0.0.1 start: `cross-env NODE_ENV=development webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mr-social-client@0.0.1 start script 'cross-env NODE_ENV=development webpack-dev-server'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the mr-social-client package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=development webpack-dev-server
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs mr-social-client
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls mr-social-client
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ec2-user/environment/hubs/npm-debug.log

**Comment by brianpeiris** [comment]
Hi Jeff. It's not entirely clear what's going wrong, but I would start by upgrading nodejs, you'll need v8 or v9

**Comment by jeffrobernard** [comment]
Here is the latest after the node update to 8 as suggested. Could installing with npm install and npm run start rather than yarn install, yarn build be causing this issue? 

`ec2-user:~/environment/hubs/src (master) $ npm run start

> mr-social-client@0.0.1 start /home/ec2-user/environment/hubs
> cross-env NODE_ENV=development webpack-dev-server

(node:3955) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
ℹ ｢wds｣: Project is running at https://172.31.92.245:8080/
ℹ ｢wds｣: webpack output is served from /
✖ ｢wdm｣: Hash: 199260ad8302dc1560af
Version: webpack 4.9.1
Time: 14721ms
Built at: 2018-05-27 17:40:28
                                                                        Asset       Size           Chunks                    Chunk Names
               assets/images/help-hud@2x-6bf5636b37144ec3d8e4a27af324f0eb.png   18.9 KiB                   [emitted]         
            assets/avatars/bot-recording-7f2546e910fe0d799b1c6fce46fc450f.mp3    950 KiB                   [emitted]  [big]  
                   assets/hud/bubble_off-fdd52ceb047cd6d4630a21133d494cce.png   8.58 KiB                   [emitted]         
              assets/hud/bubble_on-hover-0983414d57ef280d60bcffc5c42496d3.png   8.88 KiB                   [emitted]         
                    assets/hud/bubble_on-7470866ad35dd91067de4e68456f4d27.png   9.24 KiB                   [emitted]         
             assets/hud/freeze_off-hover-1f7a8ef93ec2eb2f66aef8258529c068.png   12.8 KiB                   [emitted]         
                   assets/hud/freeze_off-43648bae6c3c542fe81e01a7d4ee7ad3.png   12.2 KiB                   [emitted]         
              assets/hud/freeze_on-hover-fc009e972eed2da7d42906595b34d7c4.png   13.3 KiB                   [emitted]         
                    assets/hud/freeze_on-2adcc566824bedffd1e1dcdd5020b1c1.png   12.8 KiB                   [emitted]         
               assets/hud/mute_off-hover-d0778cd40f6a62d84550956a9eb2f802.png   6.08 KiB                   [emitted]         
                     assets/hud/mute_off-2c466a516681066572663973edaadbf7.png   4.81 KiB                   [emitted]         
                assets/hud/mute_on-hover-e0f6fda97fe9c876c9bd27b022f9a7cd.png   8.61 KiB                   [emitted]         
                      assets/hud/mute_on-3977ff9e514f05e48ef5095c90a1c3ad.png   9.57 KiB                   [emitted]         
                    assets/hud/tooltip.9-0d85679e9995e14e2c8c1d8e996eb43a.png  815 bytes                   [emitted]         
                        assets/hud/watch-6dcfde1754099e7daaebc0104b833465.glb    880 KiB                   [emitted]         
                        assets/sfx/quack-1f18502834f8f1db43990b769c2ab193.mp3   7.03 KiB                   [emitted]         
                 assets/sfx/specialquack-6d1a192a6092e8dfed5d3de063755ee2.mp3   11.6 KiB                   [emitted]         
                         assets/sfx/tone-3fa0defb5172b2533fedcc1929605799.mp3   53.9 KiB                   [emitted]         
                         assets/sfx/tone-78ae5a60f0e336f384919eee9f5a2e18.ogg   32.6 KiB                   [emitted]         
                         assets/sfx/tone-4604a4c98f36f3e0c6980295bc5c7ffe.wav    385 KiB                   [emitted]  [big]  
                        assets/sfx/tone-624e72d19fe0cea1b85ca174cb6be256.webm     32 KiB                   [emitted]         
                     assets/waternormals-4418dde3f6abc21dc32506acf5f5b093.jpg    243 KiB                   [emitted]         
                   assets/images/account-b19d3eb256285a254dc8756d5c38235e.svg  826 bytes                   [emitted]         
            assets/images/daydream_entry-618366f41fe755b753573d475cab1872.svg   8.51 KiB                   [emitted]         
         assets/images/default_thumbnail-6be4192c472c10c9a4c89e9a702895e8.png   3.23 KiB                   [emitted]         
      assets/images/desktop_screen_entry-5009d4e589b7caa7647ff89541bfbfa4.svg   1.55 KiB                   [emitted]         
              assets/images/device_entry-1536d5c288131565b19cfc3ec1d929e0.svg   3.24 KiB                   [emitted]         
                 assets/images/dice_icon-3e12cbc96fc8d27f674cfc6295b94382.svg   2.75 KiB                   [emitted]         
            assets/images/dropdown_arrow-427fb8d451998f4eec0ad543165f2a91.png  206 bytes                   [emitted]         
         assets/images/dropdown_arrow@2x-c16ca622a5bd77aec0faa2761ab8dcd6.png  302 bytes                   [emitted]         
          assets/images/expand_dots_icon-38460458e0e3638e3b45cd70ef077e4d.svg  748 bytes                   [emitted]         
              assets/images/gearvr_entry-fb3971b741d14dc6e249d698aee09812.svg   2.01 KiB                   [emitted]         
          assets/images/generic_vr_entry-3b2cc7af9be809395e3d58872d85127b.svg   2.07 KiB                   [emitted]         
                  assets/images/help-hud-4f396aacecdeab9acb5c53b63f707a87.png   11.8 KiB                   [emitted]         
             assets/hud/bubble_off-hover-7ca95a6626495863af6e4f7b9ebc04f8.png   10.4 KiB                   [emitted]         
assets/images/hub_create_button_disabled-0fa6a1bce843adf0338445c2a88047ed.svg   1.17 KiB                   [emitted]         
 assets/images/hub_create_button_enabled-035b75e10af83f79b0a9ae4759aa4ba3.svg   1.34 KiB                   [emitted]         
          assets/images/level_background-8cebbc9db1cb1c8dc0c94d7a6cf889d7.png   1.88 KiB                   [emitted]         
       assets/images/level_background@2x-2fc59ccb4e15b24227310dcc0736058e.png   3.67 KiB                   [emitted]         
                assets/images/level_fill-338fe47928b89e96b82cc651023d0dfd.png   1.71 KiB                   [emitted]         
             assets/images/level_fill@2x-dc5ec005319ba99f27e4011db035292e.png   3.38 KiB                   [emitted]         
                      assets/images/logo-8f1dfd234d060073524bc29912a24f75.svg   14.2 KiB                   [emitted]         
                assets/images/mic_denied-6f265ac615c120127ea96a42e622cabc.png   4.11 KiB                   [emitted]         
             assets/images/mic_denied@2x-7b31e5ffc307062fc2c609a33d918b9d.png   8.08 KiB                   [emitted]         
               assets/images/mic_granted-6a5d269f341348577b687a24aeea12f2.png   3.71 KiB                   [emitted]         
            assets/images/mic_granted@2x-1a2a0c515fdcfdd6ce5ee6be6f17d64f.png   7.43 KiB                   [emitted]         
                 assets/images/mic_level-65069cdb2a680e44a7888ee019abee23.png  990 bytes                   [emitted]         
              assets/images/mic_level@2x-921d16c1ae1419c3df154ffb44166839.png   2.32 KiB                   [emitted]         
                 assets/images/mic_small-3448120f12ab0cf94f8dbd4729834040.png  400 bytes                   [emitted]         
              assets/images/mic_small@2x-c9a0ac2d11eb862287e704086fe91378.png  765 bytes                   [emitted]         
       assets/images/mobile_screen_entry-f20c8908171c4d83fe220c3cad95bd26.svg   1.39 KiB                   [emitted]         
             assets/images/speaker_level-c9f33814b00c63cd9d8b7676f262ac6d.png  953 bytes                   [emitted]         
          assets/images/speaker_level@2x-bf22116041d89f49b1b3bcf7ade958da.png   2.13 KiB                   [emitted]         
              assets/images/warning_icon-6763c155fea2391899e9e5faa44d5f4d.png  582 bytes                   [emitted]         
           assets/images/warning_icon@2x-a585508ac0c8b1fbfed0bc762c628830.png   1.05 KiB                   [emitted]         
                assets/images/webvr_cube-438c09689067ed18fc9f844bf0ce11dd.svg  915 bytes                   [emitted]         
                       assets/video/home-5af051d2c531928dbaaf51b9badaabde.mp4      2 MiB                   [emitted]  [big]  
                      assets/video/home-aee18c619a9005bd4b0d31295670af80.webm   1.81 MiB                   [emitted]         
                            assets/js/avatar-selector-c27b07934614fb4ff604.js   4.23 MiB  avatar-selector  [emitted]  [big]  avatar-selector
                                        assets/js/hub-25e13b9b0d423c4f3cd0.js   11.3 MiB              hub  [emitted]  [big]  hub
                                      assets/js/index-2d473da4bc6a10d2e4fe.js   3.66 MiB            index  [emitted]  [big]  index
                                       assets/js/link-7dd1d6865c237b446bb2.js   4.03 MiB             link  [emitted]  [big]  link
                                                                   index.html  526 bytes                   [emitted]         
                                                                     hub.html   19.3 KiB                   [emitted]         
                                                                    link.html  635 bytes                   [emitted]         
                                                         avatar-selector.html  551 bytes                   [emitted]         
                                                                  favicon.ico   33.7 KiB                   [emitted]         
                                                              hub-preview.png   22.8 KiB                   [emitted]         
Entrypoint index [big] = assets/js/index-2d473da4bc6a10d2e4fe.js
Entrypoint hub [big] = assets/js/hub-25e13b9b0d423c4f3cd0.js
Entrypoint link [big] = assets/js/link-7dd1d6865c237b446bb2.js
Entrypoint avatar-selector [big] = assets/js/avatar-selector-c27b07934614fb4ff604.js
[./node_modules/aframe-input-mapping-component/src/index.js] 10.4 KiB {hub} [built]
[./node_modules/aframe-motion-capture-components/src/index.js] 464 bytes {hub} [built]
[./node_modules/webpack-dev-server/client/index.js?https://172.31.92.245:8080] (webpack)-dev-server/client?https://172.31.92.245:8080 7.75 KiB {avatar-selector} {link} {hub} {index} [built]
[./src/avatar-selector.js] 2.37 KiB {avatar-selector} [built]
[0] multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/index.js 40 bytes {index} [built]
[4] multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/hub.js 40 bytes {hub} [built]
[5] multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/link.js 40 bytes {link} [built]
[./src/utils/phoenix-utils.js] 1.94 KiB {link} {hub} [built]
[6] multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/avatar-selector.js 40 bytes {avatar-selector} [built]
[./src/hub.js] 19.7 KiB {hub} [built]
[./src/index.js] 1.02 KiB {index} [built]
[./src/link.js] 1.14 KiB {link} [built]
[./src/utils/hub-channel.js] 3.61 KiB {hub} [built]
[./src/utils/i18n.js] 705 bytes {avatar-selector} {link} {hub} {index} [built]
[./src/utils/link-channel.js] 5.47 KiB {link} {hub} [built]
    + 663 hidden modules

ERROR in ./src/assets/stylesheets/index.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/index.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/index.scss 2:14-139
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/index.js

ERROR in ./src/assets/stylesheets/hub.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/hub.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/hub.scss 2:14-137
 @ ./src/hub.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/hub.js

ERROR in ./src/assets/stylesheets/link.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/link.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/link.scss 2:14-138
 @ ./src/link.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/link.js

ERROR in ./src/assets/stylesheets/link-dialog.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/link-dialog.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/link-dialog.scss 2:14-145
 @ ./src/react-components/link-dialog.js
 @ ./src/react-components/info-dialog.js
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/index.js

ERROR in ./src/assets/stylesheets/footer.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/footer.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/footer.scss 2:14-140
 @ ./src/react-components/footer.js
 @ ./src/react-components/ui-root.js
 @ ./src/hub.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/hub.js

ERROR in ./src/assets/stylesheets/2d-hud.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/2d-hud.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/2d-hud.scss 2:14-140
 @ ./src/react-components/2d-hud.js
 @ ./src/react-components/ui-root.js
 @ ./src/hub.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/hub.js

ERROR in ./src/assets/stylesheets/avatar-selector.scss (./node_modules/css-loader??ref--6-2!./node_modules/sass-loader/lib/loader.js!./src/assets/stylesheets/avatar-selector.scss)
Module build failed: Error: ENOENT: no such file or directory, scandir '/home/ec2-user/environment/hubs/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.getInstalledBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ec2-user/environment/hubs/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:652:30)
 @ ./src/assets/stylesheets/avatar-selector.scss 2:14-149
 @ ./src/avatar-selector.js
 @ multi (webpack)-dev-server/client?https://172.31.92.245:8080 ./src/avatar-selector.js
Child html-webpack-plugin for "avatar-selector.html":
     1 asset
    Entrypoint undefined = avatar-selector.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/avatar-selector.html] 786 bytes {0} [built]
Child html-webpack-plugin for "hub.html":
                                                                Asset       Size  Chunks                    Chunk Names
        assets/hud/mute_on-hover-e0f6fda97fe9c876c9bd27b022f9a7cd.png   8.61 KiB          [emitted]         
    assets/avatars/bot-recording-7f2546e910fe0d799b1c6fce46fc450f.mp3    950 KiB          [emitted]  [big]  
           assets/hud/bubble_off-fdd52ceb047cd6d4630a21133d494cce.png   8.58 KiB          [emitted]         
      assets/hud/bubble_on-hover-0983414d57ef280d60bcffc5c42496d3.png   8.88 KiB          [emitted]         
            assets/hud/bubble_on-7470866ad35dd91067de4e68456f4d27.png   9.24 KiB          [emitted]         
     assets/hud/freeze_off-hover-1f7a8ef93ec2eb2f66aef8258529c068.png   12.8 KiB          [emitted]         
           assets/hud/freeze_off-43648bae6c3c542fe81e01a7d4ee7ad3.png   12.2 KiB          [emitted]         
      assets/hud/freeze_on-hover-fc009e972eed2da7d42906595b34d7c4.png   13.3 KiB          [emitted]         
            assets/hud/freeze_on-2adcc566824bedffd1e1dcdd5020b1c1.png   12.8 KiB          [emitted]         
       assets/hud/mute_off-hover-d0778cd40f6a62d84550956a9eb2f802.png   6.08 KiB          [emitted]         
             assets/hud/mute_off-2c466a516681066572663973edaadbf7.png   4.81 KiB          [emitted]         
     assets/hud/bubble_off-hover-7ca95a6626495863af6e4f7b9ebc04f8.png   10.4 KiB          [emitted]         
              assets/hud/mute_on-3977ff9e514f05e48ef5095c90a1c3ad.png   9.57 KiB          [emitted]         
            assets/hud/tooltip.9-0d85679e9995e14e2c8c1d8e996eb43a.png  815 bytes          [emitted]         
                assets/hud/watch-6dcfde1754099e7daaebc0104b833465.glb    880 KiB          [emitted]         
                assets/sfx/quack-1f18502834f8f1db43990b769c2ab193.mp3   7.03 KiB          [emitted]         
         assets/sfx/specialquack-6d1a192a6092e8dfed5d3de063755ee2.mp3   11.6 KiB          [emitted]         
                 assets/sfx/tone-3fa0defb5172b2533fedcc1929605799.mp3   53.9 KiB          [emitted]         
                 assets/sfx/tone-78ae5a60f0e336f384919eee9f5a2e18.ogg   32.6 KiB          [emitted]         
                 assets/sfx/tone-4604a4c98f36f3e0c6980295bc5c7ffe.wav    385 KiB          [emitted]  [big]  
                assets/sfx/tone-624e72d19fe0cea1b85ca174cb6be256.webm     32 KiB          [emitted]         
             assets/waternormals-4418dde3f6abc21dc32506acf5f5b093.jpg    243 KiB          [emitted]         
     + 1 hidden asset
    Entrypoint undefined = hub.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/hub.html] 20.2 KiB {0} [built]
    [./src/assets/avatars/bot-recording.mp3] 111 bytes {0} [built]
    [./src/assets/hud/bubble_off-hover.png] 110 bytes {0} [built]
    [./src/assets/hud/bubble_off.png] 104 bytes {0} [built]
    [./src/assets/hud/bubble_on-hover.png] 109 bytes {0} [built]
    [./src/assets/hud/bubble_on.png] 103 bytes {0} [built]
    [./src/assets/hud/freeze_off-hover.png] 110 bytes {0} [built]
    [./src/assets/hud/freeze_off.png] 104 bytes {0} [built]
    [./src/assets/hud/freeze_on-hover.png] 109 bytes {0} [built]
    [./src/assets/hud/freeze_on.png] 103 bytes {0} [built]
    [./src/assets/hud/mute_off-hover.png] 108 bytes {0} [built]
    [./src/assets/hud/mute_on-hover.png] 107 bytes {0} [built]
    [./src/assets/hud/mute_on.png] 101 bytes {0} [built]
    [./src/assets/hud/tooltip.9.png] 103 bytes {0} [built]
    [./src/assets/waternormals.jpg] 102 bytes {0} [built]
        + 8 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/index.html] 496 bytes {0} [built]
Child html-webpack-plugin for "link.html":
     1 asset
    Entrypoint undefined = link.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/link.html] 611 bytes {0} [built]
ℹ ｢wdm｣: Failed to compile.
`

**Comment by jeffrobernard** [comment]
Case closed. I was unfamiliar with Yarn, installed it with updated node and it successfully compiled.

**Comment by brianpeiris** [comment]
Glad to hear it. Let us know if you run into other issues.

**Comment by jeffrobernard** [comment]
I'm running into an issue viewing the application running in the browser. In AWS cloud 9, it shows that the app is successfully built and gives an address on port 8080. When opening link in a browser, it times out after a min. and doesn't load. I'm on a mac and have tried opening the link on safari, chrome, and firefox. What else do I need to do to get it working? It shows also shows everything running on its EC2 instance, so i'm sure its related to browser permissions. Do I need to open another ticket?
