### ISSUE TITLE
Chrome: TypeError: e.vr.setPoseTarget is not a function

### ISSUE THREAD

**Issue by InfiniteLee** [mozilla/hubs#438]
On Chrome: 
```
TypeError: e.vr.setPoseTarget is not a function
  at setPoseTarget(src/core/scene/a-scene.js:509:22)
  at apply(./node_modules/raven-js/src/raven.js:360:0)
  at dispatchEvent(src/core/a-node.js:297:15)
  at emit(src/systems/camera.js:115:12)
  at setActiveCamera(src/components/camera.js:60:13)
  at updateActiveCamera(src/components/camera.js:46:9)
  at update(src/core/component.js:280:11)
  at updateProperties(src/core/component.js:50:7)
  at call(src/core/component.js:474:14)
  at HTMLElement.value(src/core/a-entity.js:336:18)
  at initComponent(src/core/a-entity.js:492:11)
  at updateComponent(src/core/a-entity.js:461:13)
  at updateComponents(src/core/a-entity.js:259:13)
  at cb(src/core/a-node.js:129:20)
```
I suspect this is happening because we upgraded aframe last week. #418

**Comment by gfodor** [comment]
pretty sure this doesn't happen anymore
