### ISSUE TITLE
Intermittent crash on scene entry

### ISSUE THREAD

**Issue by keianhzo** [mozilla/hubs#5286]
**Description**
Sometimes when entering the scene there is an exceptions that stops client execution and avoids the user to login.

**To Reproduce**
1. Enter a Hubs scene
2. See error

**Expected behavior**
The user should always be able to enter the scene without errors

**Screenshots**

**Additional context**```
Looks like a race condition if the avatar-pov-node is not yet created but the cursor already accesses it.
```
raven.js:381 Uncaught TypeError: Cannot read properties of null (reading 'object3D')
    at n.AFRAME.registerComponent.tick2 (cursor-controller.js:111:35)
    at zk.tick (cursor-targetting-system.js:47:56)
    at i.tick (hubs-systems.js:97:33)
    at HTMLElement.value (a-scene.js:823:40)
    at HTMLElement.value (a-scene.js:867:36)
    at three.module.js:26185:35
    at r (three.module.js:12486:3)
    at a (raven.js:377:21)
```

**Comment by keianhzo** [comment]
I'll work on a way to reproduce this steadily. It seems that having and empty cache and/or slow connection may help based on your discord comment and my own experience. For some reason I just started to see it recently but I bet it's definitely affecting a lot of users.

**Comment by qiangjiadong** [comment]
Thks a lot! Once this issue solved, I think more and more mainland Chinese audience can easily create and enjoy hubs!!!

**Comment by keianhzo** [comment]
@qiangjiadong do you have any steps to reproduce this that make it happen consistently? Things like connection speed, an specific scene that you can share or steps might be helpful. I'm trying to find consistent steps but it seems to be quite random.

**Comment by qiangjiadong** [comment]
any updates?
