### ISSUE TITLE
Cannot create room when run dev client

### ISSUE THREAD

**Issue by kosukekurimoto** [mozilla/hubs#5516]
npm ci
npm run dev
and when i click "Create room"
↓
```
hub.js:219 Uncaught Error: no embed token
    at ./src/hub.js (hub.js:219:9)
    at __webpack_require__ (bootstrap:84:1)
    at checkDeferredModules (bootstrap:45:1)
    at bootstrap:221:1
    at bootstrap:221:1
```

**Comment by takahirox** [comment]
Thanks for the problem report. But unfortunately I couldn't reproduce it on my Windows 10 Chrome. What platform did you encounter the problem on?

**Comment by kosukekurimoto** [comment]
Thank you for your response

macOS Monterey 12.4
Google Chrome 
NodeJS v16.13.2

```
git clone git@github.com:mozilla/hubs.git
cd hubs
npm ci
```
↓
```
Error:
npm ERR! Invalid Version: 0.5.0a
```
↓
```
Apply this patch
https://github.com/matthewwiese/docker-mozilla-hubs/blob/main/fix-5471.patch
```
↓
```
npm ci
npm run login
npm start
```
↓
```
> hubs@0.0.1 start
> webpack-dev-server --mode=development --env.loadAppConfig

(node:7648) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
ℹ ｢wds｣: Project is running at https://localhost:8080/webpack-dev-server/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: 404s will fallback to /index.html
```
↓
```
Access to: https://localhost:8080/webpack-dev-server/
Click the Create Room button
```
↓
```
Uncaught Error: no embed token
    at ./src/hub.js (hub.js:219:9)
    at __webpack_require__ (bootstrap:84:1)
    at checkDeferredModules (bootstrap:45:1)
    at bootstrap:221:1
    at bootstrap:221:1
userinput.js:331 
```

**Comment by kosukekurimoto** [comment]
Oops, I solved it myself.

Solutions
- Use Firefox
- Access "https://localhost:8080" instead of webpack
- https://www.youtube.com/watch?v=l33b5GTrC5Q
