### ISSUE TITLE
Placing a custom GIF in-room causes the 2D UI to crash

### ISSUE THREAD

**Issue by Exairnous** [mozilla/hubs#6132]
**Description**
When you go to place a GIF in-room and click on "Custom URL or File" the Hubs 2D UI crashes.

**To Reproduce**
1. Go to the "Place" menu and choose "GIF".
2. Click on "Custom URL or File" in the top right-hand corner.
3. Observe the Hubs 2D UI go white and an error is printed in the browser console (see below).

**Expected behavior**
You should be able to input a custom URL to use for your GIF without crashing the 2D UI.

**Hardware** 
 - Device: Laptop
 - OS: Linux
 - Browser: Chromium

**Additional context**
Error message:
```
react-dom.production.min.js:189 TypeError: t.split is not a function
    at m (index.esm.mjs:69:33)
    at Fe (index.esm.mjs:1915:21)
    at ou (react-dom.production.min.js:244:482)
    at ku (react-dom.production.min.js:263:46)
    at wu (react-dom.production.min.js:260:446)
    at bu (react-dom.production.min.js:259:431)
    at react-dom.production.min.js:283:96
    at _s (react-dom.production.min.js:281:398)
    at ss (react-dom.production.min.js:273:439)
    at Ba (react-dom.production.min.js:127:105)
dl @ react-dom.production.min.js:189
n.callback @ react-dom.production.min.js:189
Ao @ react-dom.production.min.js:144
ku @ react-dom.production.min.js:262
wu @ react-dom.production.min.js:260
bu @ react-dom.production.min.js:259
(anonymous) @ react-dom.production.min.js:283
_s @ react-dom.production.min.js:281
ss @ react-dom.production.min.js:273
Ba @ react-dom.production.min.js:127
(anonymous) @ react-dom.production.min.js:267
23:50:28.799 react-dom.production.min.js:127 Uncaught TypeError: t.split is not a function
    at m (index.esm.mjs:69:33)
    at Fe (index.esm.mjs:1915:21)
    at ou (react-dom.production.min.js:244:482)
    at ku (react-dom.production.min.js:263:46)
    at wu (react-dom.production.min.js:260:446)
    at bu (react-dom.production.min.js:259:431)
    at react-dom.production.min.js:283:96
    at _s (react-dom.production.min.js:281:398)
    at ss (react-dom.production.min.js:273:439)
    at Ba (react-dom.production.min.js:127:105)
```

**Comment by keianhzo** [comment]
Fixed by https://github.com/mozilla/hubs/pull/6135
