### ISSUE TITLE
BG - Need a way to manipulate values over time / Timers in general

### ISSUE THREAD

**Issue by j-conrad** [mozilla/hubs#6294]
There are lots of uses for keeping track of time. Probably too many to mention.

Looking for a concise way to have control over time. Having something like this would also allow easier manipulation of values over time since you could use a 'seconds' output and some math to set values.

**Describe the solution you'd like**

There are likely multiple types of control needed, but a starting point would be a simple `Stopwatch` or `Timer` where you could specify the Start/End times (allowing you to count up or down), an input to trigger the Start, an input to Pause the timer, and an input to Reset the timer. The outputs needed would be 'Started', 'Paused', 'Unpaused', 'Current Time/Time Remaining' and 'Ended' (alarm).
It would also be useful to have a Boolean option for 'Loop' so the timer could automatically start over when it hits the end time.

**Describe alternatives you've considered**

I have tried using various configurations with `OnTick`, `Throttle`, and Getting/Setting variables like 'seconds'. For something so commonly needed, this becomes quite cumbersome.

**Additional context**
See Unreal's Blueprint Timer examples for further ideas/examples.

**Comment by j-conrad** [comment]
Excellent! 
One small issue: If you try to use the `Clear Timer` and don't specify a Timer ID (default `0`), it produces this crash:
`time-nodes.ts:106 Uncaught TypeError: Cannot convert a BigInt value to a number
    at D.triggered [as triggeredInner] (time-nodes.ts:106:7)
    at D.triggered (oveddan-behave-graph-core.esm.js:501:25)
    at q.executeStep (oveddan-behave-graph-core.esm.js:947:12)
    at Y.executeAllSync (oveddan-behave-graph-core.esm.js:1021:20)
    at behavior-graph.ts:267:14
    at Array.forEach (<anonymous>)
    at behavior-graph.ts:261:30
    at hubs-systems.ts:190:3
    at app.ts:242:11
    at three.module.js:27389:35`
